linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    # - cyclop
    - deadcode # (default)
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck # (default)
    - errname
    - errorlint
    - exhaustive
    # - exhaustivestruct # (deprecated)
    # - exhaustruct
    - exportloopref
    # - forbidigo
    - forcetypeassert
    # - funlen
    - gci
    # - gochecknoglobals # (cobra)
    # - gochecknoinits # (cobra)
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot # (cobra)
    - godox
    - goerr113
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    # - golint # (deprecated)
    # - gomnd # (this is hard)
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple # (default)
    - govet # (default)
    - ifshort
    - importas
    - ineffassign # (default)
    # - interfacer # (deprecated)
    - ireturn
    # - lll
    - makezero
    # - maligned # (deprecated)
    - misspell
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    # - scopelint # (deprecated)
    - sqlclosecheck
    - staticcheck # (default)
    - structcheck # (default)
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck # (default)
    - unconvert
    - unparam
    - unused # (default)
    - varcheck # (varcheck)
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl # (maintenace mode)
